### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by JasonSanford** [mapbox/open-streets-style#5]
I'm having a lot of fun with this style in TileMill although I feel like the tiling process is running a lot slower than some of my other (**much** simpler, **very** boring) styles. 

Very soon I'm going to be tiling a fairly large area (Ohio and West Virgina) down to zoom level 18. I'm looking for ways to speed up the tiling process and thought I'd see if you had any ideas. I'm exporting tiles using exact directions in the readme of this project.
- For now I'm tiling on my local machine, an iMac that's a few years old now so I'd likely move to an Ubuntu EC2 instance for production. I expect this to help some.
- It looks like a handfull of shapefiles are being used for data sources. I would assume moving these into PostGIS would help, but not sure how much and if it would be worth the effort.
- Browsing the style definitions, I see that some subqueries are being used to separate different classes of roads, highways, open spaces, etc. I plan to create indexes on the most commonly queried fields to see if that helps.

Ok, sort of rambling here, but thought I'd see if you have any quick tips before I start tiling. I'll probably test lots of different things except dumbing down the styles (they're great!).

**Comment by ajashton** [comment]
> Very soon I'm going to be tiling a fairly large area (Ohio and West Virgina) down to zoom level 18. 

Note that rendering tiles all the way down to zoom level 18 is a very intense task for anything except very small areas. An area the size of Ohio and WV will take a _very_ long time to complete (and will require many GB of disk space). TileMill, MBTiles, and the general concept of pre-caching map tiles are best suited for large areas at small scales or small areas at large scales.

If setting up a live rendering server is an option for you I would look into that, and only pre-render up to zoom-level 15 or thereabouts. The majority of tiles deeper than that will likely never be viewed.

> For now I'm tiling on my local machine, an iMac that's a few years old now so I'd likely move to an Ubuntu EC2 instance for production. I expect this to help some.

Yes - a multicore processor as fast as you can afford, and at least 8GB of RAM are a good idea for tile rendering. Fast harddrives are also a bonus but you don't really have control of that on an EC2.

> It looks like a handfull of shapefiles are being used for data sources. I would assume moving these into PostGIS would help, but not sure how much and if it would be worth the effort.

Some of these are for the coastline and a few large inland water bodies such as the great lakes. Importing them to PostGIS may not make much of a difference since Mapnik is very efficient at rendering shapefiles. What would make sense, however, is cropping these shapefiles to the area you are rendering. Doing this may be easiest from PostGIS where you can do something like:

```
create table processed_p_crop as (
  select gid, the_geom from processed_p
  where st_intersects(the_geom, st_setsrid(
    'BOX(572126 5671279,1258837 6154972)'::box2d, 900913)
  )
);
```

..replacing the coordinates inside `BOX()` with an appropriate bounding box of your data (in mercator meters).

There are also a couple of boundary shapefiles from Natural Earth in there that you might want to leave out, or at least limit to small scales. They're mostly in there as placeholders right now - the accuracy of Natural Earth data is not appropriate for street-level scales.

> Browsing the style definitions, I see that some subqueries are being used to separate different classes of roads, highways, open spaces, etc. I plan to create indexes on the most commonly queried fields to see if that helps.

Yes, this is a good idea.

**Comment by JasonSanford** [comment]
Great, this helps a lot. Thanks!
